def payload_standard(dado):
    return {
        # "Class.": float(dado["Class."]),
        "jogador": dado["Jogador"],
        "nacionalidade": dado["Nação"],
        "posicao": dado["Pos."],
        "equipe": dado["Equipe"],
        "idade": int(dado["Idade"]),
        "nascimento": None,
        
        "indices": {
            "MP": float(dado["MP"]),
            "Inícios": float(dado["Inícios"]),
            "Min.": float(dado["Min."]),
            "90s": float(dado["90s"]),
            "Gols": float(dado["Gols"]),
            "Assis.": float(dado["Assis."]),
            "G+A": float(dado["G+A"]),
            "G-PB": float(dado["G-PB"]),
            "PB": float(dado["PB"]),
            "PT": float(dado["PT"]),
            "CrtsA": float(dado["CrtsA"]),
            "CrtV": float(dado["CrtV"]),
            "xG": float(dado["xG"]),
            "npxG": float(dado["npxG"]),
            "xAG": float(dado["xAG"]),
            "npxG+xAG": float(dado["npxG+xAG"]),
            "PrgC": float(dado["PrgC"]),
            "PrgP": float(dado["PrgP"]),
            "PrgR": float(dado["PrgR"]),
            "Gols.1": float(dado["Gols.1"]),
            "Assis..1": float(dado["Assis..1"]),
            "G+A.1": float(dado["G+A.1"]),
            "G-PB.1": float(dado["G-PB.1"]),
            "G+A-PB": float(dado["G+A-PB"]),
            "xG.1": float(dado["xG.1"]),
            "xAG.1": float(dado["xAG.1"]),
            "xG+xAG": float(dado["xG+xAG"]),    
            "npxG.1": float(dado["npxG.1"]),
            "npxG+xAG.1": float(dado["npxG+xAG.1"]),
        },
        # "Partidas": "Partidas",
    }   

def payload_passing(dado):
    return {
        "Class.": float(dado["Class."]),
        "Jogador": dado["Jogador"],
        "Nação": dado["Nação"],
        "Pos.": dado["Pos."],
        "Equipe": dado["Equipe"],
        "Idade": int(dado["Idade"]),
        "Nascimento": None,
        "indices": {
            "90s": float(dado["90s"]),
            "Cmp": int(dado["Cmp"]),
            "Att": int(dado["Att"]),
            "Cmp%": float(dado["Cmp%"]),
            "DistTot": float(dado["DistTot"]),
        },
        # "Partidas": "Partidas",
    }   
